### ISSUE TITLE
A menu without properties does not display its collection sections

### ISSUE THREAD

**Issue by clembu** [Mustard2/MenuCreator#4]
As seen in the following image, a menu containing only collection sections and no properties in the `unsorted` section only shows `no properties added yet`.

![image](https://user-images.githubusercontent.com/13928490/108770225-5811cc80-755a-11eb-9558-d0cfb6ae6575.png)

---

If I just add a single property after that, I have the whole thing, collection sections included 

![image](https://user-images.githubusercontent.com/13928490/108770606-c9ea1600-755a-11eb-8219-660443c56e70.png)

**Comment by Mustard2** [comment]
This is surely a bug, I will fix it in the next version. I forgot to update that check when I added Collection sections.

**Comment by Mustard2** [comment]
I found the bug and corrected it.

Now it will show a message only if sections has not been created, not properties added.

The fix will be added in the new upcoming version.

**Comment by Mustard2** [comment]
This should be fixed in version 0.0.3.
